doc: what are the default values
kaj/nickel-jwt-session pull request #9
Opened 2016-09-22 05:18 UTC by tshepang

2016-09-30 21:24 UTC, kaj requested changes
Thanks, stating the default values is indeed a good thing to do in the docstrings.

I have a comment on the first one, the two others are fine.

2016-09-30 21:24 UTC, kaj commented on src/lib.rs
> +    /// The default is None.
"The default is to not set an issuer", would perhaps be more appropriate, as the argument isn't an Option and therefore cannot be None.  The default for the internal variable is indeed None, but that is internal.

2016-10-02 14:32 UTC, tshepang commented
review addressed

2016-10-03 05:47 UTC, merged

2016-10-03 05:47 UTC, kaj commented
Merged.  Thanks!